### ISSUE TITLE
`buffalo pop` not working in `buffalo` generated project

### ISSUE THREAD

**Issue by nscharfe** [gobuffalo/buffalo#1467]
## Description

I cannot run `buffalo pop` from within a `buffalo` generated project. If i `cd` outside of the `buffalo` generated project, it works as expected.

Note: Initially `buffalo plugins` was not working from within a generated project but upping the timeout got it working for me. Ex: `export BUFFALO_PLUGIN_TIMEOUT=2s`

### Steps to Reproduce the Problem

* Install app via `go get` or via `homebrew` (same results for both)
* Create new project via `buffalo new`. Output [here](https://gist.github.com/nscharfe/de84c36dbc315630c70ed2961a3b2a21)
* Try to install / run `pop` plugin. Output [here](https://gist.github.com/nscharfe/68389d80a847278489df4c88a0cf04ef)

### Expected Behavior

Expecting `buffalo pop` to work from within a `buffalo` generated project. Additionally, `buffalo help` does not list `pop` as a potential parameter.

### Actual Behavior

`buffalo pop` not found within a buffalo generated project.

```
~/go/src/github.com/dev/test [master] $ buffalo pop
ERRO[0002] Pop support has been moved to the https://github.com/gobuffalo/buffalo-pop plugin.

Go Get Installation:

	$ go get github.com/gobuffalo/buffalo-pop

Buffalo Plugins Installation*:

	$ buffalo plugins install github.com/gobuffalo/buffalo-pop

* Requires https://github.com/gobuffalo/buffalo-plugins installed.

 ```

Note that if i cd outside of the generated project directly, `buffalo pop` works and `buffalo help` lists `pop` as a potential parameter.

This causes `buffalo generate` commands that rely on `pop`/`db` to not work. For example, see [here](https://gist.github.com/nscharfe/43e4aa29c66a4317c8185aafa383cf6c)

### Info

<details>

```
$ buffalo info
### Buffalo Version
v0.13.6

### App Information
Pwd=/Users/nscharfe/go/src/github.com/alphaflow/test
Root=/Users/nscharfe/go/src/github.com/alphaflow/test
GoPath=/Users/nscharfe/go
Name=test
Bin=bin/test
PackagePkg=github.com/alphaflow/test
ActionsPkg=github.com/alphaflow/test/actions
ModelsPkg=github.com/alphaflow/test/models
GriftsPkg=github.com/alphaflow/test/grifts
VCS=git
WithPop=true
WithSQLite=false
WithDep=true
WithWebpack=false
WithYarn=false
WithDocker=true
WithGrifts=true
WithModules=false

### Go Version
go version go1.10.4 darwin/amd64

### Go Env
GOARCH="amd64"
GOBIN="/Users/nscharfe/go/bin"
GOCACHE="/Users/nscharfe/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nscharfe/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/st/nhlg61pn5_s7m6v7by0wjmtc0000gn/T/go-build292061869=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Node Version
v6.0.0

### NPM Version
3.8.6

### Yarn Version
1.9.4

### PostgreSQL Version
pg_ctl (PostgreSQL) 10.5

### MySQL Version
MySQL Not Found

### SQLite Version
3.24.0 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl

### Dep Version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.10.4
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false

### Dep Status
The status of 3 projects are unknown due to errors. Rerun with `-v` flag to see details.
PROJECT                                             CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
dmitri.shuralyov.com/text/kebabcase                 branch master  branch master  40e40b4   40e40b4  1  
github.com/BurntSushi/toml                          v0.3.1         v0.3.1         3012a1d   v0.3.1   1  
github.com/ajg/form                                 v1.5           v1.5           cc29540   v1.5     1  
github.com/blang/semver                             v3.5.1         v3.5.1         2ee8785   v3.5.1   1  
github.com/cockroachdb/cockroach-go                 branch master  branch master  e0a95df   e0a95df  1  
github.com/davecgh/go-spew                          v1.1.1         v1.1.1         8991bc2   v1.1.1   1  
github.com/dustin/go-humanize                       v1.0.0         v1.0.0         9f541cc   v1.0.0   1  
github.com/fatih/color                              v1.7.0         v1.7.0         5b77d2a   v1.7.0   1  
github.com/fatih/structs                            v1.1.0         v1.1.0         4966fc6   v1.1.0   1  
github.com/fsnotify/fsnotify                        v1.4.7         v1.4.7         c282820   v1.4.7   1  
github.com/go-sql-driver/mysql                      v1.4.1         v1.4.1         72cd26f   v1.4.1   1  
github.com/gobuffalo/buffalo                        ^0.13.6        v0.13.6        7dc6819   v0.13.6  5  
github.com/gobuffalo/buffalo-plugins                v1.7.0         v1.7.0         c3663ee   v1.7.0   2  
github.com/gobuffalo/buffalo-pop                    v1.1.15        v1.1.15        f4c9dd9   v1.1.15  2  
github.com/gobuffalo/envy                           v1.6.9         v1.6.9         b29bf6b   v1.6.9   1  
github.com/gobuffalo/events                         v1.1.8         v1.1.8         737cbff   v1.1.8   1  
github.com/gobuffalo/fizz                           v1.1.3         v1.1.3         8ac5462   v1.1.3   2  
github.com/gobuffalo/flect                          branch master  branch master  47375f6   47375f6  2  
github.com/gobuffalo/genny                          branch master  branch master  e8ff4ad   e8ff4ad  2  
github.com/gobuffalo/github_flavored_markdown       v1.0.7         v1.0.7         c57d0cf   v1.0.7   6  
github.com/gobuffalo/httptest                       v1.0.4         v1.0.4         f5842bb   v1.0.4   1  
github.com/gobuffalo/logger                         branch master  branch master  8e9b89b   8e9b89b  1  
github.com/gobuffalo/makr                           v1.1.5         v1.1.5         bfe5373   unknown  1  
github.com/gobuffalo/mapi                           v1.0.1         v1.0.1         09ac528   v1.0.1   1  
github.com/gobuffalo/meta                           branch master  branch master  8850e47   8850e47  1  
github.com/gobuffalo/mw-contenttype                 branch master  branch master  74f5a47   74f5a47  1  
github.com/gobuffalo/mw-csrf                        branch master  branch master  446ff26   446ff26  1  
github.com/gobuffalo/mw-forcessl                    branch master  branch master  73921ae   73921ae  1  
github.com/gobuffalo/mw-paramlogger                 branch master  branch master  d6ee392   d6ee392  1  
github.com/gobuffalo/packd                          branch master  branch master  f25c5d2   a1fb7d1  1  
github.com/gobuffalo/packr                          v1.21.2        v1.21.2        17c8598   v1.21.2  1  
github.com/gobuffalo/plush                          v3.7.22        v3.7.22        57b7dec   v3.7.22  5  
github.com/gobuffalo/pop                            v4.9.2         v4.9.2         70da249   v4.9.2   6  
github.com/gobuffalo/suite                          v2.6.0         v2.6.0         9b4d77a   v2.6.0   2  
github.com/gobuffalo/tags                           v2.0.11        v2.0.11        da5de2a   v2.0.11  3  
github.com/gobuffalo/uuid                           v2.0.5         v2.0.5         3f70165   v2.0.5   1  
github.com/gobuffalo/validate                       v2.0.3         v2.0.3         f6f3be4   v2.0.3   2  
github.com/gobuffalo/x                              branch master  branch master  14085ca   14085ca  4  
github.com/gofrs/uuid                               v3.1.2         v3.1.2         7077aa6   unknown  1  
github.com/gorilla/context                          v1.1.1         v1.1.1         08b5f42   v1.1.1   1  
github.com/gorilla/mux                              v1.6.2         v1.6.2         e3702be   v1.6.2   1  
github.com/gorilla/securecookie                     v1.1.1         v1.1.1         e59506c   v1.1.1   1  
github.com/gorilla/sessions                         v1.1.3         v1.1.3         f57b7e2   v1.1.3   1  
github.com/inconshreveable/mousetrap                v1.0           v1.0           76626ae   v1.0     1  
github.com/jackc/pgx                                v3.2.0         v3.2.0         89f1e6a   v3.2.0   6  
github.com/jmoiron/sqlx                             v1.2.0         v1.2.0         d161d7a   v1.2.0   2  
github.com/joho/godotenv                            v1.3.0         v1.3.0         23d116a   v1.3.0   1  
github.com/karrick/godirwalk                        v1.7.5         v1.7.5         2de2192   v1.7.5   1  
github.com/kballard/go-shellquote                   branch master  branch master  95032a8   95032a8  1  
github.com/konsorten/go-windows-terminal-sequences  v1.0.1         v1.0.1         5c8c8bd   v1.0.1   1  
github.com/lib/pq                                   v1.0.0         v1.0.0         4ded0e9   v1.0.0   2  
github.com/markbates/going                          v1.0.2         v1.0.2         e6789dc   v1.0.2   2  
github.com/markbates/grift                          v1.0.5         v1.0.5         ce869fe   v1.0.5   1  
github.com/markbates/hmax                           v1.0.0         v1.0.0         800e180   v1.0.0   1  
github.com/markbates/inflect                        v1.0.4         v1.0.4         24b8319   v1.0.4   1  
github.com/markbates/oncer                          branch master  branch master  05fccaa   05fccaa  1  
github.com/markbates/refresh                        v1.4.11        v1.4.11        4a01744   v1.4.11  2  
github.com/markbates/safe                           v1.0.1         v1.0.1         6fea05a   v1.0.1   1  
github.com/markbates/sigtx                          v1.0.0         v1.0.0         daa2e5f   v1.0.0   1  
github.com/mattn/go-colorable                       v0.0.9         v0.0.9         167de6b   v0.0.9   1  
github.com/mattn/go-isatty                          v0.0.4         v0.0.4         6ca4dbf   v0.0.4   1  
github.com/mattn/go-sqlite3                         v1.10.0        v1.10.0        c7c4067   v1.10.0  1  
github.com/microcosm-cc/bluemonday                  v1.0.1         v1.0.1         82c7118   v1.0.1   1  
github.com/mitchellh/go-homedir                     v1.0.0         v1.0.0         ae18d6b   v1.0.0   1  
github.com/monoculum/formam                         v3.1           v3.1           0a5cdaa   v3.1     1  
github.com/pkg/errors                               v0.8.0         v0.8.0         645ef00   v0.8.0   1  
github.com/pmezard/go-difflib                       v1.0.0         v1.0.0         792786c   unknown  1  
github.com/rs/cors                                  v1.6.0         v1.6.0         9a47f48   v1.6.0   1  
github.com/serenize/snaker                          branch master  branch master  a683aaf   a683aaf  1  
github.com/sergi/go-diff                            v1.0.0         v1.0.0         1744e29   v1.0.0   1  
github.com/shurcooL/go                              branch master  branch master  58262d1   58262d1  4  
github.com/shurcooL/go-goon                         branch master  branch master  37c2f52   37c2f52  1  
github.com/shurcooL/graphql                         branch master  branch master  16b8864   16b8864  1  
github.com/sirupsen/logrus                          v1.2.0         v1.2.0         bcd833d   v1.2.0   1  
github.com/sourcegraph/annotate                     branch master  branch master  f4cad6c   f4cad6c  1  
github.com/sourcegraph/syntaxhighlight              branch master  branch master  bd320f5   bd320f5  1  
github.com/spf13/cobra                              v0.0.3         v0.0.3         ef82de7   v0.0.3   1  
github.com/spf13/pflag                              v1.0.3         v1.0.3         298182f   v1.0.3   1  
github.com/stretchr/testify                         v1.2.2         v1.2.2         f35b8ab   v1.2.2   3  
github.com/unrolled/secure                          branch master  branch master  4b6b7cf   4b6b7cf  1  
golang.org/x/crypto                                 branch master  branch master  3d3f9f4   3d3f9f4  3  
golang.org/x/net                                    branch master  branch master  adae6a3   adae6a3  2  
golang.org/x/sync                                   branch master  branch master  42b3178   42b3178  1  
golang.org/x/sys                                    branch master  branch master  ec83556   62eef0e  2  
google.golang.org/appengine                         v1.3.0         v1.3.0         4a4468e   v1.3.0   1  
gopkg.in/yaml.v2                                    v2.2.1         v2.2.1         5420a8b   v2.2.1   1  
failed to fetch updates
Usage:
  buffalo info [flags]

Flags:
  -h, --help   help for info

ERRO[0009] Error: exit status 1


$ dep status -v
Collecting project constraints:
(1/86) dmitri.shuralyov.com/text/kebabcase
(2/86) github.com/BurntSushi/toml
(3/86) github.com/ajg/form
(4/86) github.com/blang/semver
(5/86) github.com/cockroachdb/cockroach-go
(6/86) github.com/davecgh/go-spew
(7/86) github.com/dustin/go-humanize
(8/86) github.com/fatih/color
(9/86) github.com/fatih/structs
(10/86) github.com/fsnotify/fsnotify
(11/86) github.com/go-sql-driver/mysql
(12/86) github.com/gobuffalo/buffalo
(13/86) github.com/gobuffalo/buffalo-plugins
(14/86) github.com/gobuffalo/buffalo-pop
(15/86) github.com/gobuffalo/envy
(16/86) github.com/gobuffalo/events
(17/86) github.com/gobuffalo/fizz
(18/86) github.com/gobuffalo/flect
(19/86) github.com/gobuffalo/genny
(20/86) github.com/gobuffalo/github_flavored_markdown
(21/86) github.com/gobuffalo/httptest
(22/86) github.com/gobuffalo/logger
(23/86) github.com/gobuffalo/makr
(24/86) github.com/gobuffalo/mapi
(25/86) github.com/gobuffalo/meta
(26/86) github.com/gobuffalo/mw-contenttype
(27/86) github.com/gobuffalo/mw-csrf
(28/86) github.com/gobuffalo/mw-forcessl
(29/86) github.com/gobuffalo/mw-paramlogger
(30/86) github.com/gobuffalo/packd
(31/86) github.com/gobuffalo/packr
(32/86) github.com/gobuffalo/plush
(33/86) github.com/gobuffalo/pop
(34/86) github.com/gobuffalo/suite
(35/86) github.com/gobuffalo/tags
(36/86) github.com/gobuffalo/uuid
(37/86) github.com/gobuffalo/validate
(38/86) github.com/gobuffalo/x
(39/86) github.com/gofrs/uuid
(40/86) github.com/gorilla/context
(41/86) github.com/gorilla/mux
(42/86) github.com/gorilla/securecookie
(43/86) github.com/gorilla/sessions
(44/86) github.com/inconshreveable/mousetrap
(45/86) github.com/jackc/pgx
(46/86) github.com/jmoiron/sqlx
(47/86) github.com/joho/godotenv
(48/86) github.com/karrick/godirwalk
(49/86) github.com/kballard/go-shellquote
(50/86) github.com/konsorten/go-windows-terminal-sequences
(51/86) github.com/lib/pq
(52/86) github.com/markbates/going
(53/86) github.com/markbates/grift
(54/86) github.com/markbates/hmax
(55/86) github.com/markbates/inflect
(56/86) github.com/markbates/oncer
(57/86) github.com/markbates/refresh
(58/86) github.com/markbates/safe
(59/86) github.com/markbates/sigtx
(60/86) github.com/mattn/go-colorable
(61/86) github.com/mattn/go-isatty
(62/86) github.com/mattn/go-sqlite3
(63/86) github.com/microcosm-cc/bluemonday
(64/86) github.com/mitchellh/go-homedir
(65/86) github.com/monoculum/formam
(66/86) github.com/pkg/errors
(67/86) github.com/pmezard/go-difflib
(68/86) github.com/rs/cors
(69/86) github.com/serenize/snaker
(70/86) github.com/sergi/go-diff
(71/86) github.com/shurcooL/go
(72/86) github.com/shurcooL/go-goon
(73/86) github.com/shurcooL/graphql
(74/86) github.com/sirupsen/logrus
(75/86) github.com/sourcegraph/annotate
(76/86) github.com/sourcegraph/syntaxhighlight
(77/86) github.com/spf13/cobra
(78/86) github.com/spf13/pflag
(79/86) github.com/stretchr/testify
(80/86) github.com/unrolled/secure
(81/86) golang.org/x/crypto
(82/86) golang.org/x/net
(83/86) golang.org/x/sync
(84/86) golang.org/x/sys
(85/86) google.golang.org/appengine
(86/86) gopkg.in/yaml.v2
Checking upstream projects:
(1/86) dmitri.shuralyov.com/text/kebabcase
(2/86) github.com/BurntSushi/toml
(3/86) github.com/ajg/form
(4/86) github.com/blang/semver
(5/86) github.com/cockroachdb/cockroach-go
(6/86) github.com/davecgh/go-spew
(7/86) github.com/dustin/go-humanize
(8/86) github.com/fatih/color
(9/86) github.com/fatih/structs
(10/86) github.com/fsnotify/fsnotify
(11/86) github.com/go-sql-driver/mysql
(12/86) github.com/gobuffalo/buffalo
(13/86) github.com/gobuffalo/buffalo-plugins
(14/86) github.com/gobuffalo/buffalo-pop
(15/86) github.com/gobuffalo/envy
(16/86) github.com/gobuffalo/events
(17/86) github.com/gobuffalo/fizz
(18/86) github.com/gobuffalo/flect
(19/86) github.com/gobuffalo/genny
(20/86) github.com/gobuffalo/github_flavored_markdown
(21/86) github.com/gobuffalo/httptest
(22/86) github.com/gobuffalo/logger
(23/86) github.com/gobuffalo/makr
(24/86) github.com/gobuffalo/mapi
(25/86) github.com/gobuffalo/meta
(26/86) github.com/gobuffalo/mw-contenttype
(27/86) github.com/gobuffalo/mw-csrf
(28/86) github.com/gobuffalo/mw-forcessl
(29/86) github.com/gobuffalo/mw-paramlogger
(30/86) github.com/gobuffalo/packd
(31/86) github.com/gobuffalo/packr
(32/86) github.com/gobuffalo/plush
(33/86) github.com/gobuffalo/pop
(34/86) github.com/gobuffalo/suite
(35/86) github.com/gobuffalo/tags
(36/86) github.com/gobuffalo/uuid
(37/86) github.com/gobuffalo/validate
(38/86) github.com/gobuffalo/x
(39/86) github.com/gofrs/uuid
(40/86) github.com/gorilla/context
(41/86) github.com/gorilla/mux
(42/86) github.com/gorilla/securecookie
(43/86) github.com/gorilla/sessions
(44/86) github.com/inconshreveable/mousetrap
(45/86) github.com/jackc/pgx
(46/86) github.com/jmoiron/sqlx
(47/86) github.com/joho/godotenv
(48/86) github.com/karrick/godirwalk
(49/86) github.com/kballard/go-shellquote
(50/86) github.com/konsorten/go-windows-terminal-sequences
(51/86) github.com/lib/pq
(52/86) github.com/markbates/going
(53/86) github.com/markbates/grift
(54/86) github.com/markbates/hmax
(55/86) github.com/markbates/inflect
(56/86) github.com/markbates/oncer
(57/86) github.com/markbates/refresh
(58/86) github.com/markbates/safe
(59/86) github.com/markbates/sigtx
(60/86) github.com/mattn/go-colorable
(61/86) github.com/mattn/go-isatty
(62/86) github.com/mattn/go-sqlite3
(63/86) github.com/microcosm-cc/bluemonday
(64/86) github.com/mitchellh/go-homedir
(65/86) github.com/monoculum/formam
(66/86) github.com/pkg/errors
(67/86) github.com/pmezard/go-difflib
(68/86) github.com/rs/cors
(69/86) github.com/serenize/snaker
(70/86) github.com/sergi/go-diff
(71/86) github.com/shurcooL/go
(72/86) github.com/shurcooL/go-goon
(73/86) github.com/shurcooL/graphql
(74/86) github.com/sirupsen/logrus
(75/86) github.com/sourcegraph/annotate
(76/86) github.com/sourcegraph/syntaxhighlight
(77/86) github.com/spf13/cobra
(78/86) github.com/spf13/pflag
(79/86) github.com/stretchr/testify
(80/86) github.com/unrolled/secure
(81/86) golang.org/x/crypto
(82/86) golang.org/x/net
(83/86) golang.org/x/sync
(84/86) golang.org/x/sys
(85/86) google.golang.org/appengine
(86/86) gopkg.in/yaml.v2

failed to list versions for https://github.com/gorilla/sessions: : pipe: too many open files
failed to list versions for https://github.com/spf13/pflag: : fork/exec /usr/bin/git: too many open files
failed to list versions for https://github.com/gobuffalo/github_flavored_markdown: : fork/exec /usr/bin/git: bad file descriptor

PROJECT                                             CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
dmitri.shuralyov.com/text/kebabcase                 branch master  branch master  40e40b4   40e40b4  1  
github.com/BurntSushi/toml                          v0.3.1         v0.3.1         3012a1d   v0.3.1   1  
github.com/ajg/form                                 v1.5           v1.5           cc29540   v1.5     1  
github.com/blang/semver                             v3.5.1         v3.5.1         2ee8785   v3.5.1   1  
github.com/cockroachdb/cockroach-go                 branch master  branch master  e0a95df   e0a95df  1  
github.com/davecgh/go-spew                          v1.1.1         v1.1.1         8991bc2   v1.1.1   1  
github.com/dustin/go-humanize                       v1.0.0         v1.0.0         9f541cc   v1.0.0   1  
github.com/fatih/color                              v1.7.0         v1.7.0         5b77d2a   v1.7.0   1  
github.com/fatih/structs                            v1.1.0         v1.1.0         4966fc6   v1.1.0   1  
github.com/fsnotify/fsnotify                        v1.4.7         v1.4.7         c282820   v1.4.7   1  
github.com/go-sql-driver/mysql                      v1.4.1         v1.4.1         72cd26f   v1.4.1   1  
github.com/gobuffalo/buffalo                        ^0.13.6        v0.13.6        7dc6819   v0.13.6  5  
github.com/gobuffalo/buffalo-plugins                v1.7.0         v1.7.0         c3663ee   v1.7.0   2  
github.com/gobuffalo/buffalo-pop                    v1.1.15        v1.1.15        f4c9dd9   v1.1.15  2  
github.com/gobuffalo/envy                           v1.6.9         v1.6.9         b29bf6b   v1.6.9   1  
github.com/gobuffalo/events                         v1.1.8         v1.1.8         737cbff   v1.1.8   1  
github.com/gobuffalo/fizz                           v1.1.3         v1.1.3         8ac5462   v1.1.3   2  
github.com/gobuffalo/flect                          branch master  branch master  47375f6   47375f6  2  
github.com/gobuffalo/genny                          branch master  branch master  e8ff4ad   e8ff4ad  2  
github.com/gobuffalo/github_flavored_markdown       v1.0.7         v1.0.7         c57d0cf   unknown  6  
github.com/gobuffalo/httptest                       v1.0.4         v1.0.4         f5842bb   v1.0.4   1  
github.com/gobuffalo/logger                         branch master  branch master  8e9b89b   8e9b89b  1  
github.com/gobuffalo/makr                           v1.1.5         v1.1.5         bfe5373   v1.1.5   1  
github.com/gobuffalo/mapi                           v1.0.1         v1.0.1         09ac528   v1.0.1   1  
github.com/gobuffalo/meta                           branch master  branch master  8850e47   8850e47  1  
github.com/gobuffalo/mw-contenttype                 branch master  branch master  74f5a47   74f5a47  1  
github.com/gobuffalo/mw-csrf                        branch master  branch master  446ff26   446ff26  1  
github.com/gobuffalo/mw-forcessl                    branch master  branch master  73921ae   73921ae  1  
github.com/gobuffalo/mw-paramlogger                 branch master  branch master  d6ee392   d6ee392  1  
github.com/gobuffalo/packd                          branch master  branch master  f25c5d2   a1fb7d1  1  
github.com/gobuffalo/packr                          v1.21.2        v1.21.2        17c8598   v1.21.2  1  
github.com/gobuffalo/plush                          v3.7.22        v3.7.22        57b7dec   v3.7.22  5  
github.com/gobuffalo/pop                            v4.9.2         v4.9.2         70da249   v4.9.2   6  
github.com/gobuffalo/suite                          v2.6.0         v2.6.0         9b4d77a   v2.6.0   2  
github.com/gobuffalo/tags                           v2.0.11        v2.0.11        da5de2a   v2.0.11  3  
github.com/gobuffalo/uuid                           v2.0.5         v2.0.5         3f70165   v2.0.5   1  
github.com/gobuffalo/validate                       v2.0.3         v2.0.3         f6f3be4   v2.0.3   2  
github.com/gobuffalo/x                              branch master  branch master  14085ca   14085ca  4  
github.com/gofrs/uuid                               v3.1.2         v3.1.2         7077aa6   v3.1.2   1  
github.com/gorilla/context                          v1.1.1         v1.1.1         08b5f42   v1.1.1   1  
github.com/gorilla/mux                              v1.6.2         v1.6.2         e3702be   v1.6.2   1  
github.com/gorilla/securecookie                     v1.1.1         v1.1.1         e59506c   v1.1.1   1  
github.com/gorilla/sessions                         v1.1.3         v1.1.3         f57b7e2   unknown  1  
github.com/inconshreveable/mousetrap                v1.0           v1.0           76626ae   v1.0     1  
github.com/jackc/pgx                                v3.2.0         v3.2.0         89f1e6a   v3.2.0   6  
github.com/jmoiron/sqlx                             v1.2.0         v1.2.0         d161d7a   v1.2.0   2  
github.com/joho/godotenv                            v1.3.0         v1.3.0         23d116a   v1.3.0   1  
github.com/karrick/godirwalk                        v1.7.5         v1.7.5         2de2192   v1.7.5   1  
github.com/kballard/go-shellquote                   branch master  branch master  95032a8   95032a8  1  
github.com/konsorten/go-windows-terminal-sequences  v1.0.1         v1.0.1         5c8c8bd   v1.0.1   1  
github.com/lib/pq                                   v1.0.0         v1.0.0         4ded0e9   v1.0.0   2  
github.com/markbates/going                          v1.0.2         v1.0.2         e6789dc   v1.0.2   2  
github.com/markbates/grift                          v1.0.5         v1.0.5         ce869fe   v1.0.5   1  
github.com/markbates/hmax                           v1.0.0         v1.0.0         800e180   v1.0.0   1  
github.com/markbates/inflect                        v1.0.4         v1.0.4         24b8319   v1.0.4   1  
github.com/markbates/oncer                          branch master  branch master  05fccaa   05fccaa  1  
github.com/markbates/refresh                        v1.4.11        v1.4.11        4a01744   v1.4.11  2  
github.com/markbates/safe                           v1.0.1         v1.0.1         6fea05a   v1.0.1   1  
github.com/markbates/sigtx                          v1.0.0         v1.0.0         daa2e5f   v1.0.0   1  
github.com/mattn/go-colorable                       v0.0.9         v0.0.9         167de6b   v0.0.9   1  
github.com/mattn/go-isatty                          v0.0.4         v0.0.4         6ca4dbf   v0.0.4   1  
github.com/mattn/go-sqlite3                         v1.10.0        v1.10.0        c7c4067   v1.10.0  1  
github.com/microcosm-cc/bluemonday                  v1.0.1         v1.0.1         82c7118   v1.0.1   1  
github.com/mitchellh/go-homedir                     v1.0.0         v1.0.0         ae18d6b   v1.0.0   1  
github.com/monoculum/formam                         v3.1           v3.1           0a5cdaa   v3.1     1  
github.com/pkg/errors                               v0.8.0         v0.8.0         645ef00   v0.8.0   1  
github.com/pmezard/go-difflib                       v1.0.0         v1.0.0         792786c   v1.0.0   1  
github.com/rs/cors                                  v1.6.0         v1.6.0         9a47f48   v1.6.0   1  
github.com/serenize/snaker                          branch master  branch master  a683aaf   a683aaf  1  
github.com/sergi/go-diff                            v1.0.0         v1.0.0         1744e29   v1.0.0   1  
github.com/shurcooL/go                              branch master  branch master  58262d1   58262d1  4  
github.com/shurcooL/go-goon                         branch master  branch master  37c2f52   37c2f52  1  
github.com/shurcooL/graphql                         branch master  branch master  16b8864   16b8864  1  
github.com/sirupsen/logrus                          v1.2.0         v1.2.0         bcd833d   v1.2.0   1  
github.com/sourcegraph/annotate                     branch master  branch master  f4cad6c   f4cad6c  1  
github.com/sourcegraph/syntaxhighlight              branch master  branch master  bd320f5   bd320f5  1  
github.com/spf13/cobra                              v0.0.3         v0.0.3         ef82de7   v0.0.3   1  
github.com/spf13/pflag                              v1.0.3         v1.0.3         298182f   unknown  1  
github.com/stretchr/testify                         v1.2.2         v1.2.2         f35b8ab   v1.2.2   3  
github.com/unrolled/secure                          branch master  branch master  4b6b7cf   4b6b7cf  1  
golang.org/x/crypto                                 branch master  branch master  3d3f9f4   3d3f9f4  3  
golang.org/x/net                                    branch master  branch master  adae6a3   adae6a3  2  
golang.org/x/sync                                   branch master  branch master  42b3178   42b3178  1  
golang.org/x/sys                                    branch master  branch master  ec83556   62eef0e  2  
google.golang.org/appengine                         v1.3.0         v1.3.0         4a4468e   v1.3.0   1  
gopkg.in/yaml.v2                                    v2.2.1         v2.2.1         5420a8b   v2.2.1   1  
failed to fetch updates

```

</details>

**Comment by SiTiSem** [comment]
I have exactly the same problem.

**Comment by thatguychrisw** [comment]
Same problem.

**Comment by imorti** [comment]
this also wrecks generating a resource.

**Comment by vasiliyaltunin** [comment]
same to me, it keeps complaining about 'Pop support has been moved to the https://github.com/gobuffalo/buffalo-pop plugin.

**Comment by RedPh0enix** [comment]
Confirmed on Windows 10 with latest buffalo + sqlite as at 26 Nov.

_Point GOPATH variable to %USERPROFILE%\workspaces\go_

_Point GOBIN to %USERPROFILE%\workspaces\go\bin_

**>go get -u -v -tags sqlite github.com/gobuffalo/buffalo/buffalo**
 
**>cd %USERPROFILE%\workspaces\go\src**
 
**> buffalo -h** 
Helps you build your Buffalo applications that much easier!
 
Usage:
  buffalo [command]
 
Available Commands:
  build       Builds a Buffalo binary, including bundling of assets (packr & webpack)
  destroy     destroys generated code
  dev         Runs your Buffalo app in 'development' mode
  fix         will attempt to fix a Buffalo application's API to match version v0.13.6
  generate    A collection of generators to make life easier
  help        Help about any command
  info        Prints off diagnostic information useful for debugging.
  new         Creates a new Buffalo application
  routes      Print out all defined routes
  setup       Setups a newly created, or recently checked out application.
  task        Runs your grift tasks
  test        Runs the tests for your Buffalo app. Use --force-migrations if you want to skip schema load.
  version     Print the version number of buffalo
 
Flags:
  -h, --help   help for buffalo
 
Use "buffalo [command] --help" for more information about a command.
 
**> buffalo new coke --api**
      create  .buffalo.dev.yml
      create  Dockerfile
      create  .dockerignore
      create  inflections.json
      create  actions/home.go
      create  main.go
      create  fixtures/sample.toml
      create  actions/actions_test.go
      create  actions/render.go
      create  .codeclimate.yml
      create  .env
      create  grifts/init.go
      create  README.md
      create  actions/home_test.go
      create  go.mod
      create  actions/app.go
      create  models\models.go
      create  models\models_test.go
      create  grifts\db.go
         run  go get github.com/gobuffalo/buffalo-pop
[DEPRECATED] generate.Config has been deprecated.
        Use github.com/gobuffalo/pop/genny/config instead.
         run  gofmt -w C:\Users\***\workspaces\go\src\coke\actions\actions_test.go C:\Users\***\workspaces\go\src\coke\actions\app.go C:\Users\***\workspaces\go\src\coke\actions\home.go C:\Users\***\workspaces\go\src\coke\actions\home_test.go C:\Users\***\workspaces\go\src\coke\actions\render.go C:\Users\***\workspaces\go\src\coke\grifts\db.go C:\Users\***\workspaces\go\src\coke\grifts\init.go C:\Users\***\workspaces\go\src\coke\main.go C:\Users\***\workspaces\go\src\coke\models\models.go C:\Users\***\workspaces\go\src\coke\models\models_test.go
         run  go get golang.org/x/tools/cmd/goimports
         run  go get -t ./...
         run  goimports -w C:\Users\***\workspaces\go\src\coke\actions\actions_test.go C:\Users\***\workspaces\go\src\coke\actions\app.go C:\Users\***\workspaces\go\src\coke\actions\home.go C:\Users\***\workspaces\go\src\coke\actions\home_test.go C:\Users\***\workspaces\go\src\coke\actions\render.go C:\Users\***\workspaces\go\src\coke\grifts\db.go C:\Users\***\workspaces\go\src\coke\grifts\init.go C:\Users\***\workspaces\go\src\coke\main.go C:\Users\***\workspaces\go\src\coke\models\models.go C:\Users\***\workspaces\go\src\coke\models\models_test.go
      create  .gitignore
         run  git init
Initialized empty Git repository in C:/Users/***/workspaces/go/src/coke/.git/
         run  git add .
warning: LF will be replaced by CRLF in .buffalo.dev.yml.
The file will have its original line endings in your working directory.
...
warning: LF will be replaced by CRLF in models/models_test.go.
The file will have its original line endings in your working directory.
         run  git commit -q -m Initial Commit
INFO[0331] Congratulations! Your application, coke, has been successfully built!
 
INFO[0331] You can find your new application at:
C:\Users\***\workspaces\go\src\coke
INFO[0331]
Please read the README.md file in your new application for next steps on running your application.
 
**>buffalo pop -h**
A tasty treat for all your database needs
 
Usage:
  buffalo-pop pop [flags]
  buffalo-pop pop [command]
 
Aliases:
  pop, db
 
Available Commands:
  create      Creates databases for you
  destroy     Allows to destroy generated code.
  drop        Drops databases for you
  fix         Brings pop, soda, and fizz files in line with the latest APIs
  generate    Generates config, model, and migrations files.
  migrate     Runs migrations against your database.
  reset       Drop, then recreate databases
  schema      Tools for working with your database schema
  version     current version of pop
 
Flags:
  -c, --config string   The configuration file you would like to use.
  -d, --debug           Use debug/verbose mode
  -e, --env string      The environment you want to run migrations against. Will use $GO_ENV if set. (default "development")
  -h, --help            help for pop
  -p, --path string     Path to the migrations folder (default "./migrations")
  -v, --version         Show version information
 
Use "buffalo-pop pop [command] --help" for more information about a command.
 
**> cd coke**
 
**> buffalo pop -h**
ERRO[0010] Pop support has been moved to the https://github.com/gobuffalo/buffalo-pop plugin.
 
Go Get Installation:
 
        $ go get github.com/gobuffalo/buffalo-pop
 
Buffalo Plugins Installation*:
 
        $ buffalo plugins install github.com/gobuffalo/buffalo-pop
 
* Requires https://github.com/gobuffalo/buffalo-plugins installed.

**Comment by stanislas-m** [comment]
Should be fixed with v0.13.7.

**Comment by ssheptiy** [comment]
Still having issues after upgrading to v0.13.7 on Windows 10:
* `buffalo pop` is still not recognised within the application directory (%GOPATH%/src/coke).
* `buffalo-pop pop` is recognised
* running `buffalo setup` fails with this message:
```
time="2018-11-27T10:21:16+10:30" level=info msg="--> buffalo pop create -a\n"
time="2018-11-27T10:21:33+10:30" level=error msg="Pop support has been moved to the https://github.com/gobuffalo/buffalo-pop plugin.\n\nGo Get Installation:\n\n\t$ go get github.com/gobuffalo/buffalo-pop\n\nBuffalo Plugins Installation*:\n\n\t$ buffalo plugins install github.com/gobuffalo/buffalo-pop\n\n* Requires https://github.com/gobuffalo/buffalo-plugins installed.\n"
```

**Comment by ssheptiy** [comment]
I tried running `buffalo-pop pop create -a` but got this error:
```
>buffalo-pop pop create -a
v4.9.2

[POP] 2018/11/27 10:47:11 warn - unable to load connection development: unsupported dialect 'sqlite3'
[POP] 2018/11/27 10:47:11 warn - unable to load connection test: unsupported dialect 'sqlite3'
[POP] 2018/11/27 10:47:11 warn - unable to load connection production: unsupported dialect 'sqlite3'
```

**Comment by vasiliyaltunin** [comment]
As w

> I tried running `buffalo-pop pop create -a` but got this error:
> 
> ```
> >buffalo-pop pop create -a
> v4.9.2

As workaround i suggest use soda directly, like this:
`soda create a'

and justuse soda directly 

for example 
```
buffalo g resource tests name:text descr:text author:text
soda g model tests name:text descr:text author:text
soda migrate status
soda migrate up  
soda migrate status

```
but you may be need to rebuild soda with 

`go get -u -v -tags sqlite github.com/gobuffalo/pop/soda`
`go install -tags sqlite github.com/gobuffalo/pop/soda`

or may be rebuild buffalo itself with sqlite support

`go get -u -v -tags sqlite github.com/gobuffalo/buffalo/buffalo`

**Comment by ssheptiy** [comment]
Thanks for the suggestion, @vasiliyaltunin!
```
> go get -u -v -tags sqlite github.com/gobuffalo/pop/soda
> go install -tags sqlite github.com/gobuffalo/pop/soda
> soda create -a
```
worked for me.

**Comment by stanislas-m** [comment]
The new default timeout is set to 2s. If it's not enough and your system is slower than that, you can set the `BUFFALO_PLUGIN_TIMEOUT` env var to a more appropriate value.

**Comment by ssheptiy** [comment]
Setting the BUFFALO_PLUGIN_TIMEOUT env variable to 30s worked for me.

Steps:
- set env var `BUFFALO_PLUGIN_TIMEOUT=30s`
- reopen the command prompt for the new env var value to take effect
- `cd ` to the application directory
- run `go get -u -v -tags sqlite github.com/gobuffalo/buffalo/buffalo`
- run `buffalo pop -h`
Command help is displayed as expected now!
Also, `buffalo setup` completes without errors.

It is concerning though that a timeout can have such a devastating effect (making buffalo commands unusable) without providing any warning message.

**Comment by arxdsilva** [comment]
I'm +1 on this, running on v0.13.10
