### ISSUE TITLE
getaddrinfo and docker build

### ISSUE THREAD

**Issue by nferruzzi** [gobuffalo/buffalo#1597]
## Description

Building with docker and buffalo 0.13.13 returns this warning

```
Step 6/18 : RUN buffalo build --static -o /bin/app
 ---> Running in 69baaf3ccea4
# github.com/creoapp/analytics
/tmp/go-link-434311783/000019.o: In function `mygetgrouplist':
/workdir/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-434311783/000018.o: In function `mygetgrgid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-434311783/000018.o: In function `mygetgrnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-434311783/000018.o: In function `mygetpwnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-434311783/000018.o: In function `mygetpwuid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-434311783/000004.o: In function `_cgo_18049202ccd9_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:49: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
time="2019-02-19T10:51:51Z" level=info msg="\nYour application was successfully built at /bin/app\n"
```

### Steps to Reproduce the Problem

  1. `docker build`

### Expected Behavior

a build without warnings

Let ma add some background:

I've got this warning several times in the past but the build always worked fine so I just ignored them (google for it and it looks like a legit warning with no consequence).
Unfortunately today for the first time ever the built app could not resolve any address to the services its linked too; suddenly the app was reporting problems to connect to the database, redis and mongo like they were all unreachable but they were not because I managed to work around it using env variables with hard-coded IPs . 
I use docker-compose and checked if something was broken at the network level but a simple ping from the bash of the buffallo app could resolve all hostnames properly. 

I can not say the warning in the build and my app behaviour are related, but it really looks like a problem with the getaddrinfo and now I'm scared as hell that maybe one day Ill do another build and BOOM I get the same problem for no apparent reasons. 

Any help is appreciated

**Comment by nferruzzi** [comment]
Just in case someone may be interested .. I fixed my issues by removing --static from the build  and adding `libc6-compat` 

```
....
RUN buffalo build -o /bin/app

FROM alpine
RUN apk add --no-cache bash
RUN apk add --no-cache ca-certificates
RUN apk add --no-cache libc6-compat
...
```

everything else is the same and this works without problems.

**Comment by kradalby** [comment]
I still have issues with this, after removing static and adding libc I get:
```level=error msg="lstat /go: no such file or directory"
level=info msg="Starting application at 0.0.0.0:3000"
2019/03/28 14:27:52 context canceled```
In the production container. It literally started between two builds, and now I think I have stared myself blind on what have triggered it.

**Comment by yashbhutwala** [comment]
I'm having the same issue :(

**Comment by yashbhutwala** [comment]
@kradalby @nferruzzi any other workaround?  @markbates can we reopen this?

**Comment by ihattab** [comment]
same here 
/usr/bin/ld: /tmp/go-link-359691249/000007.o: in function `mygetgrouplist':
/workdir/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetgrgid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetgrnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetpwnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetpwuid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000004.o: in function `_cgo_7e1b3c2abc8d_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:57: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by ihattab** [comment]
`/usr/bin/ld: /tmp/go-link-359691249/000007.o: in function `mygetgrouplist':
/workdir/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetgrgid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetgrnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetpwnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetpwuid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000004.o: in function `_cgo_7e1b3c2abc8d_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:57: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
`

**Comment by ihattab** [comment]
> /usr/bin/ld: /tmp/go-link-359691249/000007.o: in function `mygetgrouplist':
/workdir/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetgrgid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetgrnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetpwnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000006.o: in function `mygetpwuid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-359691249/000004.o: in function `_cgo_7e1b3c2abc8d_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:57: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by markbates** [comment]
These are common warnings, not errors. There is no workaround and we won’t address or reopen.
